### ISSUE TITLE
Sphere of Hexagons

### ISSUE THREAD

**Issue by HKunogi** [ardazishvili/Sota#5]
Would be cool to have an option for an full sphere of hexagons (with the pentagon taken into account) automatically, with an API to access in an standardized way each of the hexagons on the sphere, and perhaps ways to move and customize individual hexagons of the sphere during runtime.

**Comment by ardazishvili** [comment]
Good idea for main feature of next release.

**Comment by ardazishvili** [comment]
Dear @HKunogi , please take a look at #20. For reference polyhedron is like this
![ref](https://github.com/user-attachments/assets/1e7933f2-854e-4a9f-90b3-575ba181bc19)

**Comment by HKunogi** [comment]
Neat, ill definitely give a try soon.
