### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by mlflabs** [ardazishvili/Sota#7]
Hello, 

Just letting you know that your discord link is invalid.

Also, could you provide a general doc on how to change the grid data through code, add/remove/read grid data?  I know this is work in progress, your making changes, but just a simple explanation how to access data would be great.

Thanks for the good work, the addon looks cool.

Mike

**Comment by ardazishvili** [comment]
Hello, 

Thank you for letting me know about discord. I'll start to make proper documentation before Monday.

Meanwhile, please, let me know which language do you use and what you want to achieve. HexMesh class has `vertices_`/`normals_` accessible to sub-classes. If you need to access other data from sub-class or you want public interface (out of sub-classes), let's discuss it.
https://github.com/ardazishvili/Sota/blob/255796e73270e93743912d3f08925b02b68aca47/src/core/hex_mesh.h#L42-L43

**Comment by ardazishvili** [comment]
Broken link fixed. For documentation issue see #8

**Comment by mlflabs** [comment]
thanks
im using gdscript, just want to be able to change per tile, noting as deep/detailed as vertices.  just change and read  the type of tile, is it water, hill, grass.

**Comment by ardazishvili** [comment]
Hello, @mlflabs 

Sorry for delay. Required interface is merged in master, see [doc](https://sota.readthedocs.io/en/latest/content/getting_started/api_usage_example.html#terrain-examples). Docs are not merged in master yet, WIP. In case of new request, please open new issue
