### ISSUE TITLE
Add structured documentation

### ISSUE THREAD

**Issue by ardazishvili** [ardazishvili/Sota#8]
There is no single aggregated documentation at the moment.  Add it

**Comment by ardazishvili** [comment]
Integration of exhale/sphinx/doxygen/read-the-docs is [done](https://sota.readthedocs.io/en/latest/). doc_intro branch is used at the moment. After merge will switch to main

**Comment by HKunogi** [comment]
Would be possible to have documentation that is compatible within the engine like stated in [Godot Docs](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#writing-custom-documentation)? Maybe with some [custom icons](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#adding-custom-editor-icons) too.

**Comment by ardazishvili** [comment]
> Would be possible to have documentation that is compatible within the engine like stated in [Godot Docs](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#writing-custom-documentation)? Maybe with some [custom icons](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#adding-custom-editor-icons) too.

I definitely want to do this. Actually, I already noticed, that Sota classes have no documentation when accessed via Godot editor. I wanted to fix it and your link seems good starting point

**Comment by ardazishvili** [comment]
Let's not to extend scope of this issue. It will be enough to have working mechanism to read documentation at some hosting, like "read the docs". Actual filling of specific parts will be done on demand.

On the other hand I also expect that at the date of next release, there will be no empty/partial filled pages in documentation.
